### ISSUE TITLE
googleapi: Error 400: Provided Schema does not match. Field metrics.string.installation_timestamp is missing in new schema, invalid

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#118]
Looks like the field [moved](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/ef920cdc0c36c32b864f4f8951be7086b2c27285).

**Comment by jklukas** [comment]
cc @fbertsch @acmiyaguchi 

I assume we need to make a change in the generator to make sure we pull in both the old and new locations?

**Comment by mdboom** [comment]
Looks like it was changed from a string to a datetime timestamp in this commit: https://github.com/mozilla-mobile/fenix/commit/7aeb5f072da1b7c523523c1ae40f6d527bf88245

This isn't really something we plan to allow in Glean, but we don't currently have a good way to enforce that.

It looks like the installation ping and its metrics never made it to the release channel -- therefore I'd say we only support this in the new way.

**Comment by fbertsch** [comment]
Indeed, [looks like we changed the type](https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics). In general this is not something we supported in telemetry. We really shouldn't have allowed this since the next commit, added altogether in a rebase commit, rectified the type; so we won't actually every see _any_ data from the first commit.

In fact, from that, we shouldn't have ever seen `string` for this metric, since the single deploy that day should have only had `datetime`, since that was the latest type.

From there, I found a [commit](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/cc5a6649370f5dd613dcce81f365e61281859359#diff-0accbef0a5fe8dc81ef2935ba356d093) which reversed the type, from `datetime` to `string`. That makes me think the sort we are using for probe definitions is unstable.

**Comment by whd** [comment]
The [latest commit](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/0614f059b1bf4186ff72beeef2554a566f486ce1) appears to have restored the field to its old place.

**Comment by acmiyaguchi** [comment]
From what I understand, it field restored its original position by chance. The true type of the `installation_timestamp` field should actually be a datetime. The sorting order of commits in the probe-scraper is non-deterministic on rebase merges, since all of the commits have the same timestamp. So one (or both) of the patches above will need to merged in to completely resolve this.
