### ISSUE TITLE
bug 1645166 - Add support for "rate" metric types in Glean

### ISSUE THREAD

**Issue by chutten** [mozilla/mozilla-schema-generator#181]
"rate" metric types are coming! See Glean's implementation here: https://github.com/mozilla/glean/pull/1516

We need to generate schema for this new metric type.

Also: we should document how to add new Glean metric types.

**Comment by mdboom** [comment]
It turns out (for historical reasons) that we already have a `rate` metric type (from the original design of Glean wayyyyyy back when).  So there's nothing to do (and it actually doesn't matter that the design of the rate metric changed in the meantime).

As for documenting how to do this in general, I made https://bugzilla.mozilla.org/show_bug.cgi?id=1696188
