### ISSUE TITLE
Move to disallow list

### ISSUE THREAD

**Issue by fbertsch** [mozilla/mozilla-schema-generator#30]
The allowlist is getting quite long, a disallow list would be more succinct and would allow us to deploy new schemas as they appear.

**Comment by whd** [comment]
I just noticed that `org-mozilla-fenix-nightly` is a (different) thing that was added at some point (by this repo, since there don't appear to be MPS schemas for these) but that we're not generating BQ schemas for since it's missing from the allowlist. I filed https://github.com/mozilla/mozilla-schema-generator/pull/55 for the immediate fix, but we should perhaps prioritize this issue so we don't run into this again.

**Comment by fbertsch** [comment]
I'll work on this today, thanks for that quick fix @whd
