### ISSUE TITLE
Missing histograms in latest generated-schemas

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#62]
Current guess is something to do with the probe scraper.

	* google_bigquery_table.telemetry_main_v4_live: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:telemetry_live.main_v4. Field payload.histograms.audio_track_silence_proportion is missing in new schema, invalid
	* google_bigquery_table.telemetry_main_v4_stable: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:telemetry_stable.main_v4. Field payload.histograms.audio_track_silence_proportion is missing in new schema, invalid
	* google_bigquery_table.telemetry_saved_session_v4_live: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:telemetry_live.saved_session_v4. Field payload.histograms.key is missing in new schema, invalid
	* google_bigquery_table.telemetry_saved_session_v4_stable: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:telemetry_stable.saved_session_v4. Field payload.histograms.key is missing in new schema, invalid

**Comment by acmiyaguchi** [comment]
The first set of issues with the main ping is strange, because the field for `audio_track_silence_proportion` does seem to be in the right place in the lastest schemas generated ~3 hours ago.

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/cacc254baf4f14ccf04df0afa0ab03166b68de08/schemas/telemetry/main/main.4.bq#L13975-L13977

The second set of errors is related to #58, since the existing BigQuery schema is using the MapType generated from mps, which has the following two fields:

```
payload.histograms.key
payload.histograms.value
```

Since we added aliasing recently, the map type is replaced with a record that contains the filled in histograms, leading to an incompatible schema change.

**Comment by whd** [comment]
> The first set of issues with the main ping is strange, because the field for `audio_track_silence_proportion` does seem to be in the right place in the latest schemas generated ~3 hours ago.

I will investigate this further.

**Comment by whd** [comment]
I've figured it out. In https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/f4f0bca885565b62e544b9ce37119dc91aa8c6b6#diff-1778949213ca7cc325702ef64b3460f8R1426 we dropped these from `payload.histograms`. We now only have them in `payload.processes.content.histograms`.

**Comment by acmiyaguchi** [comment]
Looking at the history of this repository, this might align to #54. It looks like there are quite a few histograms that were dropped in that revision.
